# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
