# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_auto_20190818_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='associated_with_cart',
        ),
    ]
