# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-29 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import webshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0006_remove_cartitem_associated_with_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_additional_image',
            field=models.ImageField(null=True, upload_to=webshop.models.image_folder),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_additional_image',
            field=models.ImageField(null=True, upload_to=webshop.models.image_folder),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_additional_image',
            field=models.ImageField(null=True, upload_to=webshop.models.image_folder),
        ),
    ]
